
package View;

import controller.ControllerProjetoDB;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.ModelProjeto;

/**
 *
 * @author yasmim
 */
public class ConsultaProjetos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaProjetos
     */
    
    ModelProjeto projeto = new ModelProjeto();
    ControllerProjetoDB projetodb = new ControllerProjetoDB();
    
     public int codigo;
     public String nome;
     public String descricao;
     public String dataprazo;
     public String dataentrega;
     public int status;

    
    public ConsultaProjetos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaDadosProjetos = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        btnConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Consulta Projetos");

        tabelaDadosProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome Projeto", "Descrição", "Prazo de Entrega", "Data Entregue", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDadosProjetos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDadosProjetosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaDadosProjetos);
        if (tabelaDadosProjetos.getColumnModel().getColumnCount() > 0) {
            tabelaDadosProjetos.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVoltar.setText("<-");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 754, Short.MAX_VALUE)
                .addComponent(btnConsulta)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(325, 325, 325)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnConsulta)))
                .addContainerGap(532, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void tabelaDadosProjetosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDadosProjetosMouseClicked
        
        
        codigo = Integer.parseInt(String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 0)));
        nome = String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 1));
        descricao = String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 2));
        dataprazo = String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 3));
        dataentrega = String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 4));
        status = Integer.parseInt(String.valueOf(tabelaDadosProjetos.getModel().getValueAt(tabelaDadosProjetos.getSelectedRow(), 5)));

        
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelaDadosProjetosMouseClicked

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
       listaTodosRegistros();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaDadosProjetos;
    // End of variables declaration//GEN-END:variables

    public void listaTodosRegistros() {                
        DefaultTableModel modelo = (DefaultTableModel) tabelaDadosProjetos.getModel();
       
        // Reseta os registros da tabela
        modelo.setRowCount(0);
                
        // Lista todas as pessoas da classe pessoadb
        ArrayList<ModelProjeto> projeto = projetodb.getTodos();
        
        // Percorre a lista de pessoas recebidas e adiciona na tabela da tela
        //   tipo        apelido     arrayList de pessoas
        for (ModelProjeto auxProjeto : projeto) {
            if(auxProjeto.getProcodigo() > 0){
                modelo.addRow(new Object[]{
                    auxProjeto.getProcodigo(),
                    auxProjeto.getPronome(),
                    auxProjeto.getDescricao(),
                    auxProjeto.getProdataprazo(),
                    auxProjeto.getProdataentrega(),
                    auxProjeto.getProstatus()
                });                
//            }            
        }}
    }
    
}
