/*
 * FALTA:
   LIMPA CAMPOS
   HABILITA CAMPOS
 */
package View;

import controller.ControllerProjetoDB;
import java.awt.event.KeyEvent;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ModelProjeto;

/**
 *
 * @author djonata.serafim
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
//    ProjetosConcluidos conc = new ProjetosConcluidos();
    TarefasProjeto tarefa = new TarefasProjeto();
    ConsultaProjetos todos = new ConsultaProjetos();
    ControllerProjetoDB projetodb = new ControllerProjetoDB();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jPopupMenu7 = new javax.swing.JPopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jColorChooser1 = new javax.swing.JColorChooser();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnConsultaTarefas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNomeProj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtTempo = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtDescricao = new javax.swing.JTextArea();
        btnEdtProjeto = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        cboxStatus = new javax.swing.JComboBox<>();
        edtEntrega = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jMenuItem1.setText("jMenuItem1");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu3.setText("jMenu3");

        jMenuItem4.setText("jMenuItem4");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, 166, 36));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meus Projetos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 258, 42));

        btnConsultaTarefas.setText("Consultar Tarefas");
        btnConsultaTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaTarefasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaTarefas, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 350, 166, 42));

        jLabel4.setText("Código do Projeto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(edtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 135, -1));

        jLabel3.setText("Tempo Restante");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel5.setText("Nome do Projeto");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        edtNomeProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeProjActionPerformed(evt);
            }
        });
        getContentPane().add(edtNomeProj, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 135, -1));

        jLabel6.setText("Descrição do Projeto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 100, 20));

        btnGravar.setText("Gravar Alteracoes");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 166, 42));

        btnExcluir.setText("Excluir Projeto");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 166, 42));

        btnCancelar.setText("Cancelar Alteracoes");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 166, 42));

        edtTempo.setRequestFocusEnabled(false);
        edtTempo.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                edtTempoComponentHidden(evt);
            }
        });
        jScrollPane1.setViewportView(edtTempo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 130, -1));

        jLabel7.setText("Data de Entrega");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        edtDescricao.setColumns(20);
        edtDescricao.setRows(5);
        jScrollPane2.setViewportView(edtDescricao);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 270, -1));

        btnEdtProjeto.setText("Novo Projeto");
        btnEdtProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtProjetoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdtProjeto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 166, 42));

        btnTodos.setText("Ver Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 100, 20));

        cboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cboxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 110, -1));

        edtEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        getContentPane().add(edtEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 130, -1));

        jLabel8.setText("Status do Projeto");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultaTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaTarefasActionPerformed
      tarefa.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaTarefasActionPerformed

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void edtNomeProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeProjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeProjActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
//         if ((evt.getKeyCode() == KeyEvent.VK_ENTER) || (evt.getKeyCode() == KeyEvent.VK_TAB)) {
            if (edtCodigo.getText().equals("")) {

//                edtCodigo.setText(String.valueOf(projetodb.getUltimoCodigo("tbprojeto", "procodigo")));
                JOptionPane.showMessageDialog(null, "Codigo Invalido");
//                habilitaCampos(true);

                edtCodigo.requestFocus();
            } else {
                int codigo = Integer.parseInt(edtCodigo.getText());
                ModelProjeto projetoBanco = new ModelProjeto();
                projetoBanco = projetodb.getProjeto(codigo);
                if (projetoBanco.getProcodigo() > 0) {
                    edtNomeProj.setText(projetoBanco.getPronome());
//                    edtEntrega.setDate((java.sql.Date)projetoBanco.getProdataprazo()); GELVAZIO HELP
                    edtDescricao.setText(projetoBanco.getDescricao());

//                    habilitaCampos(true);
                    edtNomeProj.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Cliente não existe!");

//                    habilitaCampos(false);

                    edtCodigo.requestFocus();
                }
            }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        // Seta os dados da tela no modelo de produto
        
        String auxCodigo = edtCodigo.getText();
        String descricao = edtDescricao.getText();        
        String auxPrazoentrega = edtEntrega.getText();
        String nome = edtNomeProj.getText();
        String auxDataentregue = null;
        String auxStatus = "1";
        
        
        // valida campos vazios
        
            if(validaCamposVazios(auxCodigo, descricao, auxPrazoentrega )){
                int codigo = Integer.parseInt(auxCodigo);
                int status = Integer.parseInt(auxStatus);
                Instant prazo = Instant.parse(auxPrazoentrega);
                Instant entrega = Instant.parse(auxDataentregue);
                
                Date prazoentrega = Date.from(prazo);
                Date dataentregue = Date.from(entrega);
                
//                
                               
            ModelProjeto projeto = new ModelProjeto(codigo, nome, prazoentrega, dataentregue, descricao, status);

            
            ModelProjeto projetoBanco = projetodb.getProjeto(codigo);
            if (projetoBanco.getProcodigo() > 0) {
                    if(projetodb.gravarAlteracaoProjeto(projeto)){
                    JOptionPane.showMessageDialog(null, "Projeto alterado com sucesso!");            
//                    limpaCampos();
//                    habilitaCampos(false);
                      edtCodigo.requestFocus();
                    } else {
                    JOptionPane.showMessageDialog(null, "Erro ao gravar alteração no projeto!");
                    }} else {
                if(projetodb.gravarNovoProjeto(projeto)){
                    JOptionPane.showMessageDialog(null, "Produto inserido com sucesso!");            
//
////                    limpaCampos();
////
////                    habilitaCampos(false);
//
                    edtCodigo.requestFocus();
                
                    JOptionPane.showMessageDialog(null, "Erro ao inserir projeto!");
                } else {
            JOptionPane.showMessageDialog(null, "Existem campos nao preenchidos!");            
        
                }}}                         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
                // SE STATUS > 1 DAR ERRO; SE NAO PODE APAGAR

//        int codigoProduto = Integer.parseInt(edtCodigo.getText());
//
//        if (vendadb.procurarProdutoNaVenda(codigoProduto)) {
//            JOptionPane.showMessageDialog(null, "Produto já foi utilizado na venda, não pode ser excluído!");
//        } else {
//            if (produtodb.excluirProduto(codigoProduto)) {
//                JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!");
//                
//                limpaCampos();
//				
//                habilitaCampos(false);
//                
//                edtCodigo.requestFocus();
//            }
//        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
//          
//        limpaCampos();
//        habilitaCampos(false);
        edtCodigo.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEdtProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtProjetoActionPerformed
                if (edtCodigo.getText().equals("")) {

                edtCodigo.setText(String.valueOf(projetodb.getUltimoCodigo("tbprojeto", "procodigo")));

//              habilitaCampos(true);

                edtNomeProj.requestFocus();
                }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdtProjetoActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        todos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodosActionPerformed

    private void cboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxStatusActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtTempoComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_edtTempoComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_edtTempoComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsultaTarefas;
    private javax.swing.JButton btnEdtProjeto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTodos;
    private javax.swing.JComboBox<String> cboxStatus;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextArea edtDescricao;
    private javax.swing.JFormattedTextField edtEntrega;
    private javax.swing.JTextField edtNomeProj;
    private javax.swing.JTextPane edtTempo;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JPopupMenu jPopupMenu7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables

    private boolean validaCamposVazios(String codigo, String descricao, String dataentrega) {
        if(codigo.equals("")){
            return false;
        }
        
        if(descricao.equals("")){
            return false;
        }
        
        if(dataentrega.equals("")){
            return false;
        }
        
        return true;
    }
    
}
