/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author yasmi
 */
public class teste extends javax.swing.JFrame {

//    ModelProjeto projeto = new ModelProjeto();
//    ControllerProjetoDB projetodb = new ControllerProjetoDB();
    
    public teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnConsultaTarefas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        edtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edtNomeProj = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtTempo = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        edtDescricao = new javax.swing.JTextArea();
        btnEdtProjeto = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        cboxStatus = new javax.swing.JComboBox<>();
        edtEntrega = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbProjetos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(620, 400, 166, 36);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meus Projetos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 70, 258, 42);

        btnConsultaTarefas.setText("Consultar Tarefas");
        btnConsultaTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaTarefasActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultaTarefas);
        btnConsultaTarefas.setBounds(620, 350, 166, 42);

        jLabel4.setText("Código do Projeto");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 150, 98, 16);

        edtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtCodigoActionPerformed(evt);
            }
        });
        edtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                edtCodigoKeyPressed(evt);
            }
        });
        getContentPane().add(edtCodigo);
        edtCodigo.setBounds(290, 170, 135, 22);

        jLabel3.setText("Tempo Restante");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 370, 86, 16);

        jLabel5.setText("Nome do Projeto");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 280, 92, 16);

        edtNomeProj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtNomeProjActionPerformed(evt);
            }
        });
        getContentPane().add(edtNomeProj);
        edtNomeProj.setBounds(290, 298, 135, 22);

        jLabel6.setText("Descrição do Projeto");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 420, 111, 16);

        btnConsulta.setText("Consulta");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsulta);
        btnConsulta.setBounds(450, 256, 100, 20);

        btnGravar.setText("Gravar Alteracoes");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGravar);
        btnGravar.setBounds(620, 200, 166, 42);

        btnExcluir.setText("Excluir Projeto");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(620, 250, 166, 42);

        btnCancelar.setText("Cancelar Alteracoes");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(620, 300, 166, 42);

        edtTempo.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(edtTempo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(290, 392, 130, 22);

        jLabel7.setText("Data de Entrega");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 324, 86, 16);

        edtDescricao.setColumns(20);
        edtDescricao.setRows(5);
        jScrollPane2.setViewportView(edtDescricao);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(290, 442, 270, 86);

        btnEdtProjeto.setBackground(new java.awt.Color(255, 204, 204));
        btnEdtProjeto.setText("Novo Projeto");
        btnEdtProjeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdtProjetoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdtProjeto);
        btnEdtProjeto.setBounds(620, 150, 166, 42);

        btnTodos.setText("Ver Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTodos);
        btnTodos.setBounds(450, 276, 100, 20);

        cboxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxStatusActionPerformed(evt);
            }
        });
        getContentPane().add(cboxStatus);
        cboxStatus.setBounds(290, 556, 110, 22);

        edtEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        getContentPane().add(edtEntrega);
        edtEntrega.setBounds(290, 342, 130, 22);

        jLabel8.setText("Status do Projeto");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 534, 91, 16);

        tbProjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Projeto"
            }
        ));
        jScrollPane3.setViewportView(tbProjetos);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(40, 150, 222, 402);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnConsultaTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaTarefasActionPerformed
//        tarefa.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaTarefasActionPerformed

    private void edtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoActionPerformed

    private void edtCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCodigoKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_edtCodigoKeyPressed

    private void edtNomeProjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtNomeProjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtNomeProjActionPerformed

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEdtProjetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdtProjetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEdtProjetoActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodosActionPerformed

    private void cboxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnConsultaTarefas;
    private javax.swing.JButton btnEdtProjeto;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnTodos;
    private javax.swing.JComboBox<String> cboxStatus;
    private javax.swing.JTextField edtCodigo;
    private javax.swing.JTextArea edtDescricao;
    private javax.swing.JFormattedTextField edtEntrega;
    private javax.swing.JTextField edtNomeProj;
    private javax.swing.JTextPane edtTempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbProjetos;
    // End of variables declaration//GEN-END:variables
  }
